---
local_dir: "{{ playbook_dir }}/local"
local_certs_dir: "{{ local_dir }}/certs"
local_vars_dir: "{{ local_dir }}/vars"
local_kubeconfigs_dir: "{{ local_dir }}/kubeconfigs"
k8s_cluster: k8s-demo
kube_cluster_cidr: 10.200.0.0/16
public_address_cidr: "172.16.0.0/24"
private_address_cidr: "10.240.0.0/24"
domain: example.com
k8s_hostnames:
  - kubernetes
  - kubernetes.default
  - kubernetes.default.svc
  - kubernetes.default.svc.cluster
  - kubernetes.svc.cluster.local
loadbalancer: "{{ groups['loadbalancers'] | first }}.{{ domain }}"
controller_ips: "{{ groups['controllers'] | map('extract', hostvars, 'ansible_all_ipv4_addresses') | ipaddr(private_address_cidr) | list | flatten | unique }}"
clients:
  admin:
    attributes:
      cn: admin
      org: system:masters
  kube-controller-manager:
    attributes:
      cn: system:kube-controller-manager
      org: system:kube-controller-manager
  kube-proxy:
    attributes:
      cn: system:kube-proxy
      org: system:node-proxier
  kube-scheduler:
    attributes:
      cn: system:kube-scheduler
      org: system:kube-scheduler
  service-account:
    attributes:
      cn: service-accounts
      org: Kubernetes
  kubernetes:
    attributes:
      cn: kubernetes
      org: Kubernetes
    hostnames: >
      {{
        ([ '127.0.0.1', '10.32.0.1', loadbalancer, 'k8s.{}'.format(domain) ] +
        groups['loadbalancers'] +
        groups['controllers'] +
        k8s_hostnames +
        controller_ips) | unique | list
      }}
kubeconfigs:
  kube-proxy:
    apiserver: "https://{{ loadbalancer }}:6443"
    user: "{{ clients['kube-proxy']['attributes']['cn'] }}"
  kube-controller-manager:
    apiserver: "https://127.0.0.1:6443"
    user: "{{ clients['kube-controller-manager']['attributes']['cn'] }}"
  kube-scheduler:
    apiserver: "https://127.0.0.1:6443"
    user: "{{ clients['kube-scheduler']['attributes']['cn'] }}"
  admin:
    apiserver: "https://127.0.0.1:6443"
    user: "{{ clients['admin']['attributes']['cn'] }}"
