---
- hosts: localhost
  tasks:
  - include_vars:
      file: group_vars/all.yaml
  - name: Generate kubeconfig for local admin access
    shell: |
      kubectl config set-cluster {{ k8s_cluster }} \
          --certificate-authority={{ local_certs_dir }}/ca.pem \
          --embed-certs=true \
          --server=https://lb-0.example.com:6443 \
          --kubeconfig=admin.kubeconfig

      kubectl config set-credentials admin \
          --client-certificate={{ local_certs_dir }}/admin.pem \
          --client-key={{ local_certs_dir }}/admin-key.pem \
          --embed-certs=true \
          --kubeconfig=admin.kubeconfig

      kubectl config set-context default \
          --cluster={{ k8s_cluster }} \
          --user=admin \
          --kubeconfig=admin.kubeconfig

      kubectl config use-context default --kubeconfig=admin.kubeconfig
    args:
      chdir: "{{ local_dir }}"

- hosts: controllers
  tasks:
    - name: Deploy CoreDNS
      k8s:
        state: present
        definition: "{{ lookup('template', './manifests/coredns.yaml') }}"
      run_once: true

    - name: Deploy traefik CRD
      k8s:
        state: present
        definition: "{{ lookup('template', './manifests/traefik-crd.yaml') }}"
      run_once: true

    - name: Deploy traefik RBAC config
      k8s:
        state: present
        definition: "{{ lookup('template', './manifests/traefik-rbac.yaml') }}"
      run_once: true

    - name: Create traefik-ingress-controller service account
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: traefik-ingress-controller
            namespace: kube-system
      run_once: true
