---
# Copy this file to settings.yaml and change the settings to suit your needs.
memory:
  loadbalancer: 256
  worker: 1024
  controller: 1024
controllers: 2
workers: 2
domain: "example.com"
public_address_cidr: "172.16.0.0/24"
private_address_cidr: "10.240.0.0/24"