---
- hosts: localhost
  pre_tasks:
    - name: gather facts from all servers
      setup:
      delegate_to: "{{item}}"
      delegate_facts: True
      loop: "{{ groups['all'] }}"
      tags:
        - worker
  roles:
    - pki
  tags:
    - init

- hosts: all
  become: yes
  roles:
    - common

- hosts: controllers
  become: yes
  roles:
    - etcd
  tags:
    - etcd
    - control

- hosts: loadbalancers
  become: yes
  roles:
    - traefik
  tags:
    - proxy
    - loadbalancers

- hosts: controllers
  become: yes
  roles:
    - controller
  tags:
    - controller

- hosts: workers
  become: yes
  roles:
    - worker
  tags:
    - worker