---
traefik_image: registry.hub.docker.com/library/traefik
traefik_version: v2.1.4
traefik_log_level: DEBUG
traefik_k8s_apiservers: []
traefik_log_dir: /var/log/traefik
traefik_conf_dir: /etc/traefik
traefik_cert_dir: "{{ traefik_conf_dir }}/certs"
traefik_dynamic_conf_dir: "{{ traefik_conf_dir }}/conf.d"
traefik_static_conf:
  global:
    sendAnonymousUsage: false
  serversTransport:
    rootCAs:
      - "{{ traefik_cert_dir }}/ca.pem"
  log:
    level: "{{ traefik_log_level }}"
    filePath: "{{ traefik_log_dir }}/traefik.log"
  accessLog:
    filePath: "{{ traefik_log_dir }}/access.log"
  entryPoints:
    web:
      address: ":80"
      proxyProtocol:
        insecure: true
    websecure:
      address: ":443"
      proxyProtocol:
        insecure: true
    kubernetes:
      address: ":6443"
      proxyProtocol:
        insecure: true
  providers:
    file:
      directory: /etc/traefik/conf.d
      watch: true
    kubernetesCRD:
      endpoint: "https://controller-0:6443" # TODO change to load balancer IP
      certAuthFilePath: "{{ traefik_cert_dir }}/ca.pem"
      token: "{{ traefik_k8s_token | default('') }}"
  api:
    dashboard: true
traefik_dynamic_conf:
  tcp:
    routers:
      k8s_api:
        rule: "HostSNI(`{{ ansible_hostname }}.{{ domain }}`) || HostSNI(`{{ ansible_hostname }}`)"
        service: k8s_api
        entryPoints:
          - kubernetes
        tls:
          passthrough: true
    services:
      k8s_api:
        loadBalancer:
          servers: "{{ traefik_k8s_apiservers }}"
  http:
    routers:
      api_redirect:
        rule: "Host(`{{ ansible_hostname }}.{{ domain }}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
        service: api@internal
        entryPoints:
          - web
        middlewares:
          - https-redirect
      api:
        rule: "Host(`{{ ansible_hostname }}.{{ domain }}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
        service: api@internal
        entryPoints:
          - websecure
        tls: {}
    middlewares:
      https-redirect:
        redirectScheme:
          scheme: https
          permanent: true
  tls:
    certificates:
      - certFile: /etc/traefik/certs/kubernetes.pem
        keyFile: /etc/traefik/certs/kubernetes-key.pem
