---
- name: Remove {{ client }}.kubeconfig for re-generation
  ansible.builtin.file:
    path: "{{ local_kubeconfigs_dir }}/{{ client }}.kubeconfig"
    state: absent
  when: force_kubeconfig_gen is defined
  tags:
    - kubeconfig

- name: Generate kubeconfig for {{ client }}
  ansible.builtin.shell: |
    kubectl config set-cluster {{ cluster | default(k8s_cluster) }} \
        --certificate-authority={{ ca_cert | default('{}/ca.pem'.format(local_certs_dir)) }} \
        --embed-certs={{ embed_certs | default(true) | ternary('true', 'false') }} \
        --server={{ apiserver }} \
        --kubeconfig={{ client }}.kubeconfig

    kubectl config set-credentials {{ user }} \
        --client-certificate={{ client_cert | default('{}/{}.pem'.format(local_certs_dir, client)) }} \
        --client-key={{ client_key | default('{}/{}-key.pem'.format(local_certs_dir, client)) }} \
        --embed-certs={{ embed_certs | default(true) | ternary('true', 'false') }} \
        --kubeconfig={{ client }}.kubeconfig

    kubectl config set-context default \
        --cluster={{ cluster | default(k8s_cluster)  }} \
        --user={{ user }} \
        --kubeconfig={{ client }}.kubeconfig

    kubectl config use-context default --kubeconfig={{ client }}.kubeconfig
  args:
    chdir: "{{ local_kubeconfigs_dir }}"
    creates: "{{ client }}.kubeconfig"
  tags:
    - kubeconfig
