---

##
# Setup local files and directories
##

- name: Create local directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ local_vars_dir }}"
    - "{{ local_certs_dir }}"
    - "{{ local_kubeconfigs_dir }}"
  tags:
    - always

- name: Create CA config file
  copy:
    content: "{{ ca_config | to_nice_json(indent=2) }}"
    dest: "{{ cert_files['ca_config'] }}"

- name: Ensure yaml files for CA and client certs exist
  copy:
    content: ""
    dest: "{{ item }}"
    force: no
  tags:
    - always
  loop:
    - "{{ cert_files['ca'] }}"
    - "{{ cert_files['clients'] }}"

##
# Load variables
##

- name: Load CA certificate
  include_vars:
    file: "{{ cert_files['ca'] }}"
    name: ca
  tags:
    - always

- name: Load client certificates
  include_vars:
    file: "{{ cert_files['clients'] }}"
    name: client_certs
  tags:
    - always

# dynamically update list of worker certificates based number of workers
- name: Adding worker instances to client list
  set_fact:
    clients: >
      {{ clients |
        combine({
          item: {
            'hostnames': [ item ] + hostvars[item]['ansible_all_ipv4_addresses'],
            'attributes': {
              'cn': 'system:node:' + item,
              'org': 'system:nodes'
            }
          }
        })
      }}
  loop: "{{ groups['workers'] }}"
  tags:
    - worker

##
# Generate CA and client certificates
##

- name: Generate CA cert and key
  include_tasks: ca.yml
  when: >
    ca | length <= 0 or
    'key' not in ca or
    'cert' not in ca

- name: Store CA cert information
  template:
    src: ca.yaml.j2
    dest: "{{ cert_files['ca'] }}"
  when: ca_update

- name: Generate client certificates and keys
  include_tasks: client.yml
  vars:
    name: "{{ item.key }}"
    attributes: "{{ item.value['attributes'] | default({}) }}"
    hostnames: "{{ item.value['hostnames'] | default(False) }}"
  when: >
    ca_update or
    item.key not in client_certs or
    'key' not in client_certs[item.key] or
    'cert' not in client_certs[item.key]
  loop: "{{ clients | dict2items }}"

- name: Store client certs
  template:
    src: clients.yaml.j2
    dest: "{{ cert_files['clients'] }}"

- name: Generate cert files
  include_tasks: save_file.yml
  loop: "{{ client_certs | combine({ 'ca': ca }) | dict2items }}"
  loop_control:
    loop_var: cert

##
# Generate kubeconfigs
##

- name: Generate worker node kubeconfigs
  include_tasks: generate_kubeconfig.yml
  vars:
    client: "{{ item }}"
    user: "{{ clients | get_dict_value(item, 'attributes', 'cn') }}"
    apiserver: "{{ 'https://{}:6443'.format(loadbalancer) }}"
  loop: "{{ groups['workers'] }}"
  tags:
    - kubeconfig

- name: Generate k8s component kubeconfigs
  include_tasks: generate_kubeconfig.yml
  vars:
    client: "{{ item.key }}"
    user: "{{ item.value['user'] }}"
    apiserver: "{{ item.value['apiserver'] }}"
  loop: "{{ kubeconfigs | dict2items }}"
  tags:
    - kubeconfig

##
# Generate data encryption key
##

- name: Ensure local variable file exists
  copy:
    content: ""
    dest: "{{ local_vars_dir }}/controllers.yaml"
    force: no
  tags:
    - init

- name: Load local variables
  include_vars:
    file: "{{ local_vars_dir }}/controllers.yaml"
    name: kube
  tags:
    - init

- name: Generate base64 encoded key
  shell: head -c 32 /dev/urandom | base64
  register: encryption_key
  when: "'encryption_key' not in kube"
  tags:
    - init

- set_fact:
    kube: "{{ kube | default({}) | combine({'encryption_key': encryption_key.stdout}) }}"
  when: "'encryption_key' not in kube"
  tags:
    - init

- name: Save to local var file
  copy:
    content: "{{ kube | to_nice_yaml(indent=2, explicit_start=True) }}"
    dest: "{{ local_vars_dir }}/controllers.yaml"
  tags:
    - init