---
- name: Create kubernetes directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
  loop:
    - "{{ kube_lib_dir }}"
    - "{{ kube_etc_dir }}"
    - "/home/vagrant/.kube"
  tags:
    - configuration

# move this to a handler or make conditional based on
# output of: kubectl version --client  --short -o json
- name: Download kubectl binary
  get_url:
    url: "{{ kube_release_url }}/kubectl"
    dest: /usr/local/bin/kubectl
    mode: 0755
    force: "{{ force_kubectl_download | default(false) | ternary('yes', 'no') }}"