---
- name: Reload systemd
  systemd:
    daemon_reload: yes
  listen:
    - update etcd service

- name: Gather service facts
  service_facts:
  listen:
    - update etcd service
    - restart etcd

- name: Restart etcd (if running)
  service:
    name: etcd
    state: restarted
  when: ansible_facts.services['etcd.service']['state'] == "running"
  listen:
    - update etcd service
    - restart etcd
