---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  listen:
    - update etcd service

- name: Gather service facts
  ansible.builtin.service_facts:
  listen:
    - update etcd service
    - restart etcd

- name: Restart etcd (if running)
  ansible.builtin.service:
    name: etcd
    state: restarted
  when: ansible_facts.services['etcd.service']['state'] == "running"
  listen:
    - update etcd service
    - restart etcd
