---
- name: Pull kube-controller-manager container image
  containers.podman.podman_image:
    name: "{{ kube_controller_manager_image }}"
    tag: "{{ kube_controller_manager_version }}"
  tags:
    - container
    - download

- name: Copy kube-controller-manager kubeconfig to {{ kube_lib_dir }}
  ansible.builtin.copy:
    src: "{{ local_kubeconfigs_dir }}/kube-controller-manager.kubeconfig"
    dest: "{{ kube_lib_dir }}/kube-controller-manager.kubeconfig"
    mode: 0640

- name: Copy kube-controller-manager certs to {{ kube_lib_dir }}
  ansible.builtin.copy:
    src: "{{ local_certs_dir }}/{{ item }}"
    dest: "{{ kube_lib_dir }}"
    mode: 0640
  loop:
    - kube-controller-manager.pem
    - kube-controller-manager-key.pem

- name: Create kube-controller-manager service file
  ansible.builtin.template:
    src: kube-controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service

- name: Enable and start kube-controller-manager
  ansible.builtin.service:
    name: kube-controller-manager
    state: started
    enabled: yes