---
- name: Pull kube-apiserver container image
  containers.podman.podman_image:
    name: "{{ kube_apiserver_image }}"
    tag: "{{ kube_apiserver_version }}"
  tags:
    - container
    - download

- name: Create kube-apiserver service file
  ansible.builtin.template:
    src: kube-apiserver.service.j2
    dest: /etc/systemd/system/kube-apiserver.service

- name: Enable and start kube-apiserver
  ansible.builtin.service:
    name: kube-apiserver
    state: started
    enabled: yes