---
- name: Load kube-scheduler variables
  include_vars:
    file: kube_scheduler.yaml

- name: Pull kube-scheduler container image
  podman_image:
    name: "{{ kube_scheduler_image }}"
    tag: "{{ kube_scheduler_version }}"
  tags:
    - container

- name: Generate kubeconfig for kube-scheduler
  shell: |
    kubectl config set-cluster {{ cluster }} \
        --certificate-authority=ca.pem \
        --embed-certs=true \
        --server=https://127.0.0.1:6443 \
        --kubeconfig=kube-scheduler.kubeconfig

    kubectl config set-credentials {{ clients['kube-scheduler']['attributes']['cn'] }} \
        --client-certificate=kube-scheduler.pem \
        --client-key=kube-scheduler-key.pem \
        --embed-certs=true \
        --kubeconfig=kube-scheduler.kubeconfig

    kubectl config set-context default \
        --cluster={{ cluster }} \
        --user={{ clients['kube-scheduler']['attributes']['cn'] }} \
        --kubeconfig=kube-scheduler.kubeconfig

    kubectl config use-context default --kubeconfig=kube-scheduler.kubeconfig
  args:
    chdir: "{{ kube_lib_dir }}"
    creates: kube-scheduler.kubeconfig

- name: Create KubeSchedulerConfiguration
  copy:
    dest: "{{ kube_scheduler_config_file }}"
    content: "{{ kube_scheduler_config_content | to_nice_yaml(indent=2) }}"
    mode: 0640

- name: Create kube-scheduler service file
  template:
    src: kube-scheduler.service.j2
    dest: /etc/systemd/system/kube-scheduler.service

- name: Enable and start kube-scheduler
  systemd:
    name: kube-scheduler
    state: started
    enabled: yes