---
- name: Pull kube-scheduler container image
  podman_image:
    name: "{{ kube_scheduler_image }}"
    tag: "{{ kube_scheduler_version }}"
  tags:
    - container
    - download

- name: Copy kube-scheduler kubeconfig to {{ kube_lib_dir }}
  copy:
    src: "{{ local_kubeconfigs_dir }}/kube-scheduler.kubeconfig"
    dest: "{{ kube_lib_dir }}/kube-scheduler.kubeconfig"
    mode: 0640

- name: Copy kube-scheduler certs to {{ kube_lib_dir }}
  copy:
    src: "{{ local_certs_dir }}/{{ item }}"
    dest: "{{ kube_lib_dir }}"
    mode: 0640
  loop:
    - kube-scheduler.pem
    - kube-scheduler-key.pem

- name: Create KubeSchedulerConfiguration
  copy:
    dest: "{{ kube_scheduler_config_file }}"
    content: "{{ kube_scheduler_config_content | to_nice_yaml(indent=2) }}"
    mode: 0640

- name: Create kube-scheduler service file
  template:
    src: kube-scheduler.service.j2
    dest: /etc/systemd/system/kube-scheduler.service

- name: Enable and start kube-scheduler
  systemd:
    name: kube-scheduler
    state: started
    enabled: yes