---
- name: Pull kube-apiserver container image
  podman_image:
    name: "{{ kube_apiserver_image }}"
    tag: "{{ kube_apiserver_version }}"
  tags:
    - container
    - download

- name: Create kube-apiserver service file
  template:
    src: kube-apiserver.service.j2
    dest: /etc/systemd/system/kube-apiserver.service

- name: Enable and start kube-apiserver
  systemd:
    name: kube-apiserver
    state: started
    enabled: yes