---
- name: Load kube-apiserver variables
  include_vars:
    file: kube_apiserver.yaml

- name: Pull kube-apiserver container image
  podman_image:
    name: "{{ kube_apiserver_image }}"
    tag: "{{ kube_apiserver_version }}"
  tags:
    - container

- name: Create kube-apiserver service file
  template:
    src: kube-apiserver.service.j2
    dest: /etc/systemd/system/kube-apiserver.service
#   notify:
#     - update traefik service