---
- name: Load kube-controller-manager variables
  include_vars:
    file: kube_controller_manager.yaml

- name: Pull kube-controller-manager container image
  podman_image:
    name: "{{ kube_controller_manager_image }}"
    tag: "{{ kube_controller_manager_version }}"
  tags:
    - container

- name: Generate kubeconfig for kube-controller-manager
  shell: |
    kubectl config set-cluster {{ cluster }}\
        --certificate-authority=ca.pem \
        --embed-certs=true \
        --server=https://127.0.0.1:6443 \
        --kubeconfig=kube-controller-manager.kubeconfig

    kubectl config set-credentials {{ clients['kube-controller-manager']['attributes']['cn'] }} \
        --client-certificate=kube-controller-manager.pem \
        --client-key=kube-controller-manager-key.pem \
        --embed-certs=true \
        --kubeconfig=kube-controller-manager.kubeconfig

    kubectl config set-context default \
        --cluster={{ cluster }}\
        --user={{ clients['kube-controller-manager']['attributes']['cn'] }} \
        --kubeconfig=kube-controller-manager.kubeconfig

    kubectl config use-context default --kubeconfig=kube-controller-manager.kubeconfig
  args:
    chdir: "{{ kube_lib_dir }}"
    creates: kube-controller-manager.kubeconfig

- name: Create kube-controller-manager service file
  template:
    src: kube-controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service

- name: Enable and start kube-controller-manager
  systemd:
    name: kube-controller-manager
    state: started
    enabled: yes