---
- name: Pull etcd container image
  containers.podman.podman_image:
    name: "{{ etcd_image }}"
    tag: "{{ etcd_version }}"
  tags:
    - container
    - download

- name: Ensure etcd host directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0750
  loop:
    - "{{ etcd_data_dir }}"
    - "{{ etcd_cert_dir }}"
  tags:
    - configuration

- name: Add ca cert
  ansible.builtin.copy:
    src: "{{ etcd_ca_cert }}"
    dest: "{{ etcd_cert_dir }}"
    mode: 0640
  tags:
    - configuration
    - pki

- name: Add etcd tls cert
  ansible.builtin.copy:
    src: "{{ etcd_tls_cert }}"
    dest: "{{ etcd_cert_dir }}"
    mode: 0640
  tags:
    - configuration
    - pki

- name: Add etcd tls key
  ansible.builtin.copy:
    src: "{{ etcd_tls_key }}"
    dest: "{{ etcd_cert_dir }}"
    mode: 0640
  tags:
    - configuration
    - pki

- name: Create etcd.conf.yaml
  ansible.builtin.template:
    src: etcd.conf.yaml.j2
    dest: "{{ etcd_conf_dir }}/etcd.conf.yaml"
    mode: 0640
  notify:
    - restart etcd

- name: Generate etcd service file
  ansible.builtin.template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
  notify:
    - update etcd service

- name: Enable and start etcd
  ansible.builtin.service:
    name: etcd
    state: started
    enabled: yes
