---
certs_dir: "{{ playbook_dir }}/certs"
cert_files:
  ca_config: "{{ certs_dir }}/ca-config.json"
  ca: "{{ certs_dir }}/ca.yaml"
  clients: "{{ certs_dir }}/clients.yaml"
cert_update: false
ca_config:
  signing:
    default:
      expiry: 8760h
    profiles:
      kubernetes:
        usages:
          - signing
          - key encipherment
          - server auth
          - client auth
        expiry: 8760h
csr:
  CN: "{{ cn | default('Kubernetes') }}"
  key:
    algo: rsa
    size: 2048
  names:
    - C: US
      L: Baltimore
      O: "{{ org | default('Kubernetes') }}"
      OU: "{{ org_unit | default('Kubernetes The Hard Way') }}"
      ST: Maryland
k8s_hostnames:
  - kubernetes
  - kubernetes.default
  - kubernetes.default.svc
  - kubernetes.default.svc.cluster
  - kubernetes.svc.cluster.local