---
- name: Create container config directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: 0750

- name: Create containerd config
  ansible.builtin.copy:
    content: "{{ containerd_config }}"
    dest: /etc/containerd/config.toml

- name: Start and enable containerd service
  ansible.builtin.service:
    name: containerd
    state: started
    enabled: yes