---
- name: Create container config directory
  file:
    path: /etc/containerd
    state: directory
    mode: 0750

- name: Create containerd config
  copy:
    content: "{{ containerd_config }}"
    dest: /etc/containerd/config.toml

- name: Start and enable containerd service
  systemd:
    name: containerd
    state: started
    enabled: yes