---
- include_vars:
    file: kubelet.yaml

- name: Download kubelet binary
  get_url:
    url: "{{ kube_release_url }}/kubelet"
    dest: /usr/local/bin/kubelet
    mode: 0755
    force: "{{ force_kubelet_download | default(false) | ternary('yes', 'no') }}"

- name: Create kubeconfig and kubelet lib directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
  loop:
    - "{{ kubelet_lib_dir }}"

- name: Copy certs to {{ kubelet_lib_dir }}
  copy:
    src: "{{ local_certs_dir }}/{{ item }}"
    dest: "{{ kubelet_lib_dir }}"
    mode: 0640
  loop:
    - "{{ ansible_hostname }}.pem"
    - "{{ ansible_hostname }}-key.pem"

- name: Create kubelet configuration
  copy:
    content: "{{ kubelet_config | to_nice_yaml(indent=2) }}"
    dest: "{{ kubelet_config_file }}"

- name: Copy {{ ansible_hostname }}'s kubeconfig
  copy:
    src: "{{ local_kubeconfigs_dir }}/{{ ansible_hostname }}.kubeconfig"
    dest: "{{ kubelet_lib_dir }}/kubeconfig"

- name: Create kubelet service file
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service

- name: Enable and start kubelet
  systemd:
    name: kubelet
    state: started
    enabled: yes