---
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - socat
    - conntrack
    - ipset
    - containerd
  tags:
    - package

- name: Copy certs to {{ kube_lib_dir }}
  copy:
    src: "{{ local_certs_dir }}/{{ item }}"
    dest: "{{ kube_lib_dir }}"
    mode: 0640
  loop:
    - ca.pem
    - "{{ ansible_hostname }}.pem"
    - "{{ ansible_hostname }}-key.pem"

- name: Disable swap
  sysctl:
    name: vm.swappiness
    value: '0'
    sysctl_set: yes

- name: Setup pod cidr network routes
  command: "route add -net {{ kube_cluster_cidr | ipsubnet(kube_pod_cidr_prefix, (item.split('-')[-1] | int)) }} gw {{ hostvars[item]['ansible_all_ipv4_addresses'] | ipaddr(private_address_cidr) | first }}"
  loop: "{{ groups['workers'] | difference([ansible_hostname]) }}"
  ignore_errors: yes

- name: Configure containerd
  include_tasks: containerd.yml

- name: Configure cni
  include_tasks: cni.yml

- name: Setup kubelet
  include_tasks: kubelet.yml

- name: Setup kube-proxy
  include_tasks: kube_proxy.yml