---
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - socat
    - conntrack
    - ipset
    - containerd
  tags:
    - package
    - download

- name: Copy certs to {{ kube_lib_dir }}
  copy:
    src: "{{ local_certs_dir }}/{{ item }}"
    dest: "{{ kube_lib_dir }}"
    mode: 0640
  loop:
    - ca.pem
    - "{{ ansible_hostname }}.pem"
    - "{{ ansible_hostname }}-key.pem"

- name: Disable swap
  sysctl:
    name: vm.swappiness
    value: '0'
    sysctl_set: yes

- name: Configure static routes
  include_tasks: networking.yml

- name: Configure containerd
  include_tasks: containerd.yml

- name: Configure cni
  include_tasks: cni.yml

- name: Setup kubelet
  include_tasks: kubelet.yml
  tags:
    - download

- name: Setup kube-proxy
  include_tasks: kube_proxy.yml
  tags:
    - download