---
- name: Install required packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop:
    - socat
    - conntrack
    - ipset
    - containerd
  tags:
    - package
    - download

- name: Copy certs to {{ kube_lib_dir }}
  ansible.builtin.copy:
    src: "{{ local_certs_dir }}/{{ item }}"
    dest: "{{ kube_lib_dir }}"
    mode: 0640
  loop:
    - ca.pem
    - "{{ ansible_hostname }}.pem"
    - "{{ ansible_hostname }}-key.pem"

- name: Disable swap
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '0'
    sysctl_set: yes

- name: Configure static routes
  ansible.builtin.include_tasks: networking.yaml

- name: Configure containerd
  ansible.builtin.include_tasks: containerd.yaml

- name: Configure cni
  ansible.builtin.include_tasks: cni.yaml

- name: Setup kubelet
  ansible.builtin.include_tasks: kubelet.yaml
  tags:
    - download

- name: Setup kube-proxy
  ansible.builtin.include_tasks: kube_proxy.yaml
  tags:
    - download