---
etcd_image: gcr.io/etcd-development/etcd
etcd_version: v3.4.3
etcd_data_dir: /var/lib/etcd
etcd_conf_dir: /etc/etcd
etcd_cert_dir: "{{ etcd_conf_dir }}/certs"
etcd_cluster_token: etcd-cluster-0
etcd_cluster_state: new
etcd_cert_name: kubernetes
etcd_tls_cert: "{{ hostvars['localhost']['client_certs'][etcd_cert_name]['cert'] }}"
etcd_tls_key: "{{ hostvars['localhost']['client_certs'][etcd_cert_name]['key'] }}"
etcd_ca_cert: "{{ hostvars['localhost']['ca']['cert'] }}"
