---
- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Set /etc/hosts entries for cluster
  template:
    src: etc/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
