---
- name: Set /etc/hosts entries for cluster
  template:
    src: etc/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
  tags:
    - configuration

- name: Add apt-key for OpenSUSE repo
  apt_key:
    url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_{{ ansible_distribution_version }}/Release.key
    state: present
  tags:
    - package
    - download

- name: Add podman repo
  apt_repository:
    repo: deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/ /
    filename: devel:kubic:libcontainers:stable.list
  tags:
    - package
    - download

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
  tags:
    - package
    - download

- name: Install podman and pip3
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - podman
    - python3-pip
  tags:
    - package
    - download

- name: Install openshift python module
  pip:
    name: openshift
  tags:
    - package
    - download