---
kubelet_lib_dir: /var/lib/kubelet
kubelet_config_file: "{{ kubelet_lib_dir }}/kubelet-config.yaml"
kubelet_config:
  kind: KubeletConfiguration
  apiVersion: kubelet.config.k8s.io/v1beta1
  authentication:
    anonymous:
      enabled: false
    webhook:
      enabled: true
    x509:
      clientCAFile: "{{ kube_ca_cert }}"
  authorization:
    mode: Webhook
  clusterDomain: "cluster.local"
  clusterDNS:
    - "10.32.0.10"
  podCIDR: "{{ kube_pod_cidr }}"
  resolvConf: "/run/systemd/resolve/resolv.conf"
  runtimeRequestTimeout: "15m"
  tlsCertFile: "/var/lib/kubelet/{{ ansible_hostname }}.pem"
  tlsPrivateKeyFile: "/var/lib/kubelet/{{ ansible_hostname }}-key.pem"
kubelet_service_config:
  config: "{{ kubelet_config_file }}"
  container-runtime: remote
  container-runtime-endpoint: unix:///var/run/containerd/containerd.sock
  image-pull-progress-deadline: 2m
  kubeconfig: "{{ kubelet_lib_dir }}/kubeconfig"
  network-plugin: cni
  register-node: true
  v: 2