---
kube_pod_cidr_prefix: 24
kube_pod_cidr: "{{ kube_cluster_cidr | ipsubnet(kube_pod_cidr_prefix, (ansible_hostname.split('-')[-1] | int)) }}"
containerd_config: |
  [plugins]
    [plugins.cri.containerd]
      snapshotter = "overlayfs"
      [plugins.cri.containerd.default_runtime]
        runtime_type = "io.containerd.runtime.v1.linux"
        runtime_engine = "/usr/local/bin/runc"
        runtime_root = ""